# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "my-terraform-state-bucket-01dc"
    key     = "./terraform.tfstate"
    region  = "us-east-1"
    encrypt = true

  }
}
